# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpeedTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SpeedTest
	pod 'ReactiveCocoa', '2.4.7'
  target 'SpeedTestTests' do

    inherit! :search_paths
    # Pods for testing
  end

  target 'SpeedTestUITests' do

    inherit! :search_paths
    # Pods for testing
  end

end
